name: Secrets

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: print secret
          run: echo "The secret is ${{ secrets.MY_SECRET }}"
        - name: add secret to .env file
          run: echo "MY_SECRET=${{ secrets.MY_SECRET }}" >> .env
        - name: Count the amount of characters
          run: wc -c .env